---
apiVersion: v1
kind: Namespace
metadata:
  name: web-app
  labels:
    app: web-app
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
  namespace: web-app
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: {{.Values.container.image}}
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env: 
        - name: UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: AUTHOR
          value: {{.Values.author}}
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /author
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 20        
      
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app
  namespace: web-app
spec:
  type: ClusterIP
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: web-app
    